<?php 
	require 'functions/sqlfunctions.php';
	session_start();
//Pull Session and Get Variables
	if(isset($_SESSION['username']))
	{
		$username = $_SESSION['username'];
	}
	else
	{
		$username = '';
	}

	$difficulty = 1;
	if(isset($_POST['difficulty']))
	{
		$difficulty = $_POST['difficulty'];
	}

	$score = 4;
	if(isset($_POST['score']))
	{
		$score = $_POST['score'];
	}

	$health = 100;
	if(isset($_POST['health']))
	{
		$health = $_POST['health'];
	}
//Submit Defeated Data
	$index = 0;
	$playerDeathInLevel = 0;
	while(isset($_POST[$index]))
	{
		$element = JSON_decode($_POST[$index], TRUE);
		$element1 = $element["e"];
		$element2 = $element["u"];
		$element3 = $element["playerDeath"];
		if($element3 == 1)
		{
			$playerDeathInLevel = 1;
		}
		submitMySQLData("
			INSERT INTO defeated (hazard_name, username, player_death)
			VALUES ('$element1', '$element2', $element3);
			");
		$index++;
	}
	if($playerDeathInLevel == 1)
	{
		$difficulty = 1;
		$score = 4;
	}

//Submit Played On Data
	if(isset($_POST['rating']) && isset($_POST['level']) && isset($_POST['seed']) && isset($_POST['score']) && isset($_POST['difficulty']) && isset($_SESSION['username']))
	{
		$se = $_POST['seed'];
		$di = $_POST['difficulty'];
		$le = $_POST['level'];
		$ra = $_POST['rating'];
		$sc = $_POST['score'];
		$playerDeathInLevel;

		submitMySQLData("
			INSERT INTO random_seed (seed, difficulty, level_type)
			VALUES ($se, $di, '$le');
			");

		submitMySQLData("
			INSERT INTO played_on (username, seed, difficulty, level_type, rating, score, died)
			VALUES ('$username', $se, $di, '$le', $ra, $sc, $playerDeathInLevel);
			");
	}


//Get Arms
	$arms = "Unarmed";
	$equipped_arms = "Empty";
	$playerDamage = 1;
	if(isset($_POST['arms']))
	{
		$arms = $_POST['arms'];
		$equipped_arms = retreiveMySQLData("
			SELECT item.item_name as 'name', rarity, equipment_type, value, effect
			FROM item
			INNER JOIN equipment
			ON item.item_name = equipment.item_name
			WHERE item.item_name = 'Pistol';
			");
		$playerDamage = $equipped_arms[0]["value"];
	}
	if($arms != "Unarmed")
	{
		
	}

//Get Armor
	$armor = "Unarmored";
	$equipped_armor = "Empty";
	$playerProtection = 0;
	if(isset($_POST['armor']))
	{
		$armor = $_POST['armor'];
		$equipped_armor = retreiveMySQLData("
			SELECT item.item_name as 'name', rarity, equipment_type, value, effect
			FROM item
			INNER JOIN equipment
			ON item.item_name = equipment.item_name
			WHERE item.item_name = '$armor';
			");
		$playerProtection = $equipped_armor[0]["value"];
	}
	if($armor != "Unarmored")
	{
		
	}

//Set The Seed
	$s = retreiveMySQLData("
		SELECT MAX(seed)
		FROM random_seed;
		");

	$seed = rand();//$s + 1

//Set the Level
	$levelSelection = retreiveMySQLData("
		SELECT *
		FROM level;
		");

	$r_value = rand(0,count($levelSelection)-1);


	$level = $levelSelection[$r_value]["level_type"]; //later generated by $levelSelection

//Get the enemy list
	$enemy_table = retreiveMySQLData("
		SELECT hazard.hazard_name as 'name', rare_spawn_rate, difficulty, enemy_type as 'type', aggression, base_damage as 'damage', health,
		spawn_rate/(SELECT SUM(spawn_rate)
					FROM hazard_spawn_table
					INNER JOIN hazard
					ON hazard_spawn_table.hazard_name = hazard.hazard_name
					INNER JOIN enemy
					ON hazard.hazard_name = enemy.hazard_name
					WHERE level_type = '$level' AND minimum_difficulty <= $difficulty) as 'spawn_rate'
		FROM hazard_spawn_table
		INNER JOIN hazard
		ON hazard_spawn_table.hazard_name = hazard.hazard_name
		INNER JOIN enemy
		ON hazard.hazard_name = enemy.hazard_name
		WHERE level_type = '$level' AND minimum_difficulty <= $difficulty
		ORDER BY spawn_rate;
		");

	for($i = 0 ; $i < count($enemy_table); $i++)
	{
		$name = $enemy_table[$i]['name'];

		$enemy_c_drop = retreiveMySQLData("
			SELECT item.item_name as 'name', rarity, effect,
			 drop_rate/(SELECT SUM(drop_rate)
			 			FROM drop_table
						INNER JOIN item
						ON drop_table.item_name = item.item_name
						INNER JOIN consumable
						ON drop_table.item_name = consumable.item_name
						WHERE hazard_name = '$name' AND rarity <= $score) as 'drop_rate'
			FROM drop_table
			INNER JOIN item
			ON drop_table.item_name = item.item_name
			INNER JOIN consumable
			ON drop_table.item_name = consumable.item_name
			WHERE hazard_name = '$name' AND rarity <= $score
			ORDER BY drop_rate;
			");


		$enemy_table[$i]['c_drop_list'] = $enemy_c_drop;

		$enemy_e_drop = retreiveMySQLData("
			SELECT item.item_name as 'name', rarity, equipment_type, value, effect, 
			 drop_rate/(SELECT SUM(drop_rate)
						FROM drop_table
						INNER JOIN item
						ON drop_table.item_name = item.item_name
						INNER JOIN equipment
						ON drop_table.item_name = equipment.item_name
						WHERE hazard_name = '$name' AND rarity <= $score) as 'drop_rate'
			FROM drop_table
			INNER JOIN item
			ON drop_table.item_name = item.item_name
			INNER JOIN equipment
			ON drop_table.item_name = equipment.item_name
			WHERE hazard_name = '$name' AND rarity <= $score
			ORDER BY drop_rate;
			");

		//print_r($enemy_e_drop);

		$enemy_table[$i]['e_drop_list'] = $enemy_e_drop;
	}
	
	//print_r($enemy_table); echo "<br />";

//Get the trap list
	$trap_table = retreiveMySQLData("
		SELECT hazard.hazard_name as 'name', rare_spawn_rate, difficulty, trap_type as 'type', effect, activation,
		spawn_rate/(SELECT SUM(spawn_rate)
					FROM hazard_spawn_table
					INNER JOIN hazard
					ON hazard_spawn_table.hazard_name = hazard.hazard_name
					INNER JOIN trap
					ON hazard.hazard_name = trap.hazard_name
					WHERE level_type = '$level' AND minimum_difficulty <= $difficulty) as 'spawn_rate'
		FROM hazard_spawn_table
		INNER JOIN hazard
		ON hazard_spawn_table.hazard_name = hazard.hazard_name
		INNER JOIN trap
		ON hazard.hazard_name = trap.hazard_name
		WHERE level_type = '$level' AND minimum_difficulty <= $difficulty
		ORDER BY spawn_rate;
		");
	
	//print_r($trap_table); echo "<br />";

//Get the consumable treasure list
	$consumable_table = retreiveMySQLData("
		SELECT item.item_name as 'name', rarity, effect, 
		spawn_rate/(SELECT SUM(spawn_rate)
					FROM treasure_spawn
					INNER JOIN item
					ON treasure_spawn.item_name = item.item_name
					INNER JOIN consumable
					ON treasure_spawn.item_name = consumable.item_name
					WHERE level_type = '$level' AND rarity <= $score
					 ) as 'drop_rate'
		FROM treasure_spawn
		INNER JOIN item
		ON treasure_spawn.item_name = item.item_name
		INNER JOIN consumable
		ON treasure_spawn.item_name = consumable.item_name
		WHERE level_type = '$level' AND rarity <= $score
		ORDER BY spawn_rate;
		");
	
	//print_r($consumable_table); echo "<br />";

//Get the equipment treasure list
	$equipment_table = retreiveMySQLData("
		SELECT item.item_name as 'name', rarity, equipment_type, value, effect,
		spawn_rate/(SELECT SUM(spawn_rate)
					FROM treasure_spawn
					INNER JOIN item
					ON treasure_spawn.item_name = item.item_name
					INNER JOIN equipment
					ON treasure_spawn.item_name = equipment.item_name
					WHERE level_type = '$level' AND rarity <= $score) as 'drop_rate'
		FROM treasure_spawn
		INNER JOIN item
		ON treasure_spawn.item_name = item.item_name
		INNER JOIN equipment
		ON treasure_spawn.item_name = equipment.item_name
		WHERE level_type = '$level' AND rarity <= $score
		ORDER BY spawn_rate;
		");
	
	//print_r($equipment_table); echo "<br />";

 ?>

<!DOCTYPE html>
<html>
	<?php include 'templates/header.php'; ?>
		<script type="text/javascript">

			var username = "<?php echo $username; ?>";
			var score = "<?php echo $score; ?>";
			var difficulty = "<?php echo $difficulty; ?>";
			var playerHealth = "<?php echo $health; ?>";
			var playerArms = "<?php echo $arms; ?>";
			var playerDamage = "<?php echo $playerDamage; ?>";
			var playerArmor = "<?php echo $armor; ?>";
			var playerProtection = "<?php echo $playerProtection; ?>";
			var seed = "<?php echo $seed; ?>";
			var level = "<?php echo $level; ?>";

			const enemyTable = JSON.parse('<?= json_encode($enemy_table); ?>');
			const trapTable = JSON.parse('<?= json_encode($trap_table); ?>');
			const consumableTable = JSON.parse('<?= json_encode($consumable_table); ?>');
			const equipmentTable = JSON.parse('<?= json_encode($equipment_table); ?>');

		</script>
		<script type="text/javascript" src = "scripts/functions.js"> </script>
		<script type="text/javascript" src = "scripts/main.js"> </script>
	<?php include 'templates/footer.php'; ?>
</html>